remove tab use spaces, some renamings, remove double used build-scripts repo

diff --git a/gluon-mesh-vpn-wireguard/files/lib/gluon/gluon-mesh-wireguard/checkuplink b/gluon-mesh-vpn-wireguard/files/lib/gluon/gluon-mesh-wireguard/checkuplink
--- a/gluon-mesh-vpn-wireguard/files/lib/gluon/gluon-mesh-wireguard/checkuplink
+++ b/gluon-mesh-vpn-wireguard/files/lib/gluon/gluon-mesh-wireguard/checkuplink
@@ -1,30 +1,27 @@
 #!/bin/sh
 
-#Wurde bereits ein privatekey generiert?
-temp=$(uci get wireguard.wireguard.privatekey);
-#Falls nicht, wird das hier nachgeholt
+# generate private key if not exists
+temp=$(uci get wireguard.wireguard.privatekey)
 if [ "$?" -ne "0" ]; then
-        uci set wireguard.wireguard.privatekey=$(wg genkey);
+        uci set wireguard.wireguard.privatekey=$(wg genkey)
         uci commit wireguard
 fi
 
-#Ist wireguard überhaupt aktiviert??
 if [ "$(uci get wireguard.wireguard.enabled)" == "true" ] || [ "$(uci get wireguard.wireguard.enabled)" == "1" ]; then
 
-        #Ab hier kommen die Tests, ob die Verbindung steht
+        # todo refactor to default CONNECTED=0
         CONNECTED=1
-
         INTERFACE=$(uci get wireguard.wireguard.iface)
 
         # Wireguardinterface vorhanden???
-        ip addr show dev $INTERFACE > /dev/null
+        ip addr show dev $INTERFACE >/dev/null
         if [ $? != 0 ]; then
                 CONNECTED=0
         fi
 
         # Gretapinterface vorhanden??
         if [ $CONNECTED != 0 ]; then
-                ip addr show dev gre > /dev/null
+                ip addr show dev gre >/dev/null
                 if [ $? != 0 ]; then
                         CONNECTED=0
                 fi
@@ -32,7 +29,7 @@ if [ "$(uci get wireguard.wireguard.enabled)" == "true" ] || [ "$(uci get wiregu
 
         # Funktioniert das Gretapinterface ueberhaupt? Also gehen Daten rueber?
         if [ $CONNECTED != 0 ]; then
-                RXBYTES=$(ip -statistics link show dev gre |  sed '4q;d' | awk '{print $1}')
+                RXBYTES=$(ip -statistics link show dev gre | sed '4q;d' | awk '{print $1}')
                 if [ $RXBYTES == 0 ]; then
                         CONNECTED=0
                 fi
@@ -40,75 +37,82 @@ if [ "$(uci get wireguard.wireguard.enabled)" == "true" ] || [ "$(uci get wiregu
 
         # Und funktioniert das Wireguardinterface? Kann ich den Server erreichen?
         if [ $CONNECTED != 0 ]; then
-                ping -c1 -w2  $(uci get wireguard.wireguard.gretapip)
+                ping -c1 -w2 $(uci get wireguard.wireguard.gretapip)
                 if [ $? != 0 ]; then
                         CONNECTED=0
                 fi
         fi
-	
-        # Wenn die Tests fehlgeschlagen sind, neu connecten
+
+        # connect / reconnect if tests failed
         if [ $CONNECTED == 0 ]; then
 
-		# Falls ein Fehler bei Wireguard war, Module entladen und neuladen
-		rmmod wireguard
-		sleep 1
-		modprobe wireguard
+                # Falls ein Fehler bei Wireguard war, Module entladen und neuladen
+                rmmod wireguard
+                sleep 2
+                modprobe wireguard
 
-        	#Wieviele Hosts gibts denn in der Config?                                                          
-        	MAX=10                                                                                             
-        	ANZAHL=0                                                                                           
-        	AUSWAHL=0                                                                                          
-       	 	until [ $ANZAHL -eq $MAX ]                                                                         
-       	 	do                                                                                                 
-                	ANZAHL=`expr $ANZAHL + 1`                                                                  
-                	uci show wireguard.peer_$ANZAHL 2>/dev/null > /dev/null                                    
-                	if [ $? != 0 ]; then                                                                       
-                        	break                                                                              
-                	fi                                                                                         
-        	done                                                                                               
-        	ANZAHL=`expr $ANZAHL - 1`                                                                          
-                                                                                                           
-        	#Und welchen nehmen wir jetzt??                                                                    
-        	SPEED1=0                                                                                           
-        	I=0                                                                                                
-        	until [ $I -eq $ANZAHL ]                                                                           
-        	do                                                                                                 
-                	I=`expr $I + 1`                                                                            
-                	#Von allen Servern die durschnittliche potenzielle Geschwindigkeit pro Wireguard-Verbindung
-                	URL=$(uci get wireguard.peer_$I.endpoint | cut -d':' -f1)                        
-			SPEED2=$(curl https://$URL/speed.php -k)                                           
-                	if [ $SPEED2 -gt $SPEED1 ]              # Wenn aktueller Server hoehren Wert hat,
-                        		then AUSWAHL=$I                 # Servernummer speichern                 
-                        	SPEED1=$SPEED2                                                           
-                	fi                                                                               
-        	done                                                                                     
-        	URL=$(uci get wireguard.peer_$AUSWAHL.endpoint | cut -d':' -f1)                          
-                                                                                                 
-		#Die alten peers loeschen
-		wg set $INTERFACE peer  $(wg |  awk 'BEGIN {RS=""} /endpoint/ {print $2}') remove
-                batctl if del gre
-                ip link delete dev gre
-                ip link delete dev $INTERFACE
+                #todo sn broker
+                #todo bond with 2 sn connections
+
+                # get random wireguard endpoint url in range of configured wireguard peers, try 10 times max
+                HTTP_CODE=0
+                COUNTER=0
+                until [ $HTTP_CODE -eq 200 ] || [ $COUNTER -eq 10 ]
+                do
+                        WG_PEER_NUMBER=$(awk -v min=1 -v max=$(uci show wireguard | grep -c endpoint) 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+                        URL=$(uci get wireguard.peer_$WG_PEER_NUMBER.endpoint | cut -d':' -f1)
+                        HTTP_CODE=$(curl -s -k -w ''%{http_code}'' https://$URL/wireguard.php)
+                        COUNTER=`expr $COUNTER + 1`
+                        sleep 5
+                done
+
+                if [ $HTTP_CODE -ne 200 ]; then
+                        echo "Error, can't connect to some supernode."
+                        exit 1;
+                fi
+
+                # delete old peers
+                wg set $INTERFACE peer $(wg | awk 'BEGIN {RS=""} /endpoint/ {print $2}') remove &> /dev/null
+                batctl if del gre &> /dev/null
+                ip link delete dev gre &> /dev/null
+                ip link delete dev $INTERFACE &> /dev/null
+
                 PUBLICKEY=$(uci get wireguard.wireguard.privatekey | wg pubkey)
-                echo $(uci get wireguard.wireguard.privatekey) > /tmp/wgpriv
+                echo $(uci get wireguard.wireguard.privatekey) > /root/wgpriv
 
-                # Public Key zum vorher ausgesuchten Server hochladen
+                # push wg public key to sn
                 IP=$(curl -s -k --data-urlencode "pubkey=$PUBLICKEY" https://$URL/wireguard.php)
-		ip link add dev $INTERFACE type wireguard
-                ip address add dev $INTERFACE $IP/16
-                wg set $INTERFACE private-key /tmp/wgpriv
-                sleep 5
+                if expr "$IP" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' > /dev/null; then
+                        for i in 1 2 3 4; do
+                                if [ $(echo "$IP" | cut -d. -f$i) -gt 255 ]; then
+                                        echo "Error, ""$IP"" is not a valid ip."
+                                        exit 1
+                                fi
+                        done
+                        # do nothing here, ip is ok
+                else
+                        echo "Error, ""$IP"" is not a valid ip."
+                        exit 1
+                fi
 
-                wg set $INTERFACE peer $(uci get wireguard.peer_$AUSWAHL.publickey) persistent-keepalive 25 allowed-ips $(uci get wireguard.wireguard.gretapip)/32 endpoint $(uci get wireguard.peer_$AUSWAHL.endpoint)
+                ip link add dev $INTERFACE type wireguard
+                ip address add dev $INTERFACE $IP/16
+                wg set $INTERFACE private-key /root/wgpriv
+
+                sleep 6
+
+                wg set $INTERFACE peer $(uci get wireguard.peer_$WG_PEER_NUMBER.publickey) persistent-keepalive 26 allowed-ips $(uci get wireguard.wireguard.gretapip)/32 endpoint $(uci get wireguard.peer_$WG_PEER_NUMBER.endpoint)
                 ip link set up dev $INTERFACE
 
-                sleep 5
+                sleep 6
+
                 ip link add gre type gretap local $IP remote $(uci get wireguard.wireguard.gretapip)
                 ip link set up dev gre
-                sleep 5
+
+                sleep 6
+
                 batctl if add gre
                 iptables -A INPUT -i $INTERFACE -j ACCEPT
                 iptables -A FORWARD -i $INTERFACE -j ACCEPT
-
         fi
 fi
